/* Renders index.html from content.json. Markup and class names follow the Bou
   canvas artboards; all copy comes from the content object, never from here. */

const esc = (value) =>
  String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

/** Escaped, with **double asterisks** turned into <strong>. */
const rich = (value) => esc(value).replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');

/** Escaped, with newlines turned into line breaks — for display headings. */
const multiline = (value) => esc(value).split('\n').join('<br>');

const arrow = '<span aria-hidden="true">&#8594;</span>';

const button = (cta, style) =>
  `<a class="btn btn-${style}" href="${esc(cta.href)}">${esc(cta.label)} ${arrow}</a>`;

const tile = (image, cls) =>
  `<span class="tile ${cls}"><img src="${esc(image.src)}" alt="${esc(image.alt)}" loading="lazy"></span>`;

export function renderPage(c) {
  const navLinks = (cls) =>
    c.nav.map((item) => `<a class="${cls}" href="${esc(item.href)}">${esc(item.label)}</a>`).join('\n      ');

  const turnstile = c.contact.form.turnstileSiteKey;

  return `<!doctype html>
<!-- Generated by build.mjs from content.json — edit content.json, not this file. -->
<html lang="${esc(c.site.lang)}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(c.site.title)}</title>
<meta name="description" content="${esc(c.site.description)}">
<meta name="theme-color" content="${esc(c.site.themeColor)}">

<meta property="og:type" content="website">
<meta property="og:title" content="${esc(c.site.ogTitle)}">
<meta property="og:description" content="${esc(c.site.ogDescription)}">
<meta property="og:image" content="${esc(c.site.ogImage)}">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Allura&family=Anton&family=Archivo:wght@400;500;700;800&family=Lekton:wght@400;700&family=Tinos:wght@400;700&display=swap">
<link rel="stylesheet" href="assets/css/styles.css">
</head>
<body>

<a class="skip-link" href="#top">Skip to content</a>

<header class="site-header band band-dark">
  <div class="inner header-inner">
    <a class="wordmark wordmark-sm" href="#top">${esc(c.brand.wordmark)}<span class="dot" aria-hidden="true"></span><span class="sr-only"> — home</span></a>

    <nav class="nav-desktop" aria-label="Primary">
      ${navLinks('eb')}
      ${button(c.cta, 'invert')}
    </nav>

    <button class="nav-toggle" type="button" aria-label="Open menu" aria-expanded="false" aria-controls="mobile-menu">
      <span class="nav-toggle-bars" aria-hidden="true"><span></span><span></span></span>
    </button>
  </div>

  <div class="mobile-menu" id="mobile-menu" hidden>
    <nav aria-label="Mobile">
      ${navLinks('d')}
      ${button(c.cta, 'invert')}
    </nav>
  </div>
</header>

<main id="top">

<!-- ============ HERO ============ -->
<section class="band band-dark hero">
  <div class="hero-media" aria-hidden="true">
    <img src="${esc(c.hero.image.src)}" alt="" loading="eager" fetchpriority="high">
    <span class="hero-scrim"></span>
  </div>
  <div class="inner hero-inner">
    <p class="eb hero-eyebrow">${esc(c.hero.eyebrow)}</p>
    <div>
      <p class="w hero-kicker">${esc(c.hero.kicker)}</p>
      <h1 class="d hero-title">${multiline(c.hero.title)}</h1>
    </div>
    <p class="lede-bold hero-lede">${esc(c.hero.lede)}</p>
    <p class="mono hero-services">${esc(c.hero.services)}</p>
    <div class="btn-row">
      ${c.hero.buttons.map((b) => button(b, b.style)).join('\n      ')}
    </div>
  </div>
</section>

<!-- ============ WHO ARE WE ============ -->
<section class="band band-cream section-about" id="about">
  <div class="inner about-grid">
    <div class="about-main">
      <p class="eb muted">${esc(c.about.eyebrow)}</p>
      <h2 class="d about-title">${multiline(c.about.title)}</h2>
      <p class="lede">${rich(c.about.lede)}</p>
      <div>
        <span class="rule-accent" aria-hidden="true"></span>
        <p class="lede-bold">${esc(c.about.statement)}</p>
      </div>
    </div>

    <div class="about-aside">
      <p class="eb muted">${esc(c.about.touchpointsTitle)}</p>
      <ul class="tp">
        ${c.about.touchpoints.map((t) => `<li><span>${esc(t)}</span></li>`).join('\n        ')}
      </ul>
      <p class="mono muted about-note">${esc(c.about.note)}</p>
    </div>
  </div>
</section>

<!-- ============ SERVICES ============ -->
<section class="band band-dark band-cobalt section-services" id="services">
  <div class="inner stack-lg">
    <div class="section-head">
      <div class="stack-sm">
        <p class="eb">${esc(c.services.eyebrow)}</p>
        <h2 class="d services-title">${multiline(c.services.title)}</h2>
      </div>
      <p class="lede section-head-note">${esc(c.services.note)}</p>
    </div>

    <div class="services-grid">
      ${c.services.columns
        .map(
          (col) => `<div>
        <h3 class="d card-title">${esc(col.title)}</h3>
        <ul class="svc">
          ${col.items.map((i) => `<li><span>${esc(i)}</span></li>`).join('\n          ')}
        </ul>
      </div>`
        )
        .join('\n      ')}
    </div>

    <div class="services-foot">
      <p class="w services-statement">${multiline(c.services.statement)}</p>
      ${button(c.services.cta, 'invert')}
    </div>
  </div>
</section>

<!-- ============ WORK ============ -->
<section class="band band-cream section-work" id="work">
  <div class="inner stack-lg">
    <div class="section-head">
      <div class="stack-sm">
        <p class="eb muted">${esc(c.work.eyebrow)}</p>
        <h2 class="d work-title">${esc(c.work.title)}</h2>
      </div>
      <p class="mono muted section-head-note">${esc(c.work.note)}</p>
    </div>

    <div class="work-grid">
      <figure class="work-feature">
        ${tile(c.work.feature.image, 'tile-feature')}
        <figcaption>
          <span class="eb signal">${esc(c.work.feature.kicker)}</span>
          <span class="d card-title">${esc(c.work.feature.title)}</span>
          <span class="ph muted">${esc(c.work.feature.result)}</span>
        </figcaption>
      </figure>

      <div class="work-small-grid">
        ${c.work.items
          .map(
            (item) => `<figure>
          ${tile(item.image, 'tile-portrait')}
          <figcaption>
            <span class="eb signal eb-xs">${esc(item.kicker)}</span>
            <span class="ph">${esc(item.client)}</span>
          </figcaption>
        </figure>`
          )
          .join('\n        ')}
      </div>
    </div>

    <div class="work-foot">
      <p class="mono ph muted">${esc(c.work.footNote)}</p>
      ${button(c.work.cta, 'outline')}
    </div>
  </div>
</section>

<!-- ============ PROCESS ============ -->
<section class="band band-dark band-cobalt section-process" id="process">
  <div class="inner process-grid">
    <div class="process-intro">
      <p class="eb">${esc(c.process.eyebrow)}</p>
      <h2 class="d process-title">${multiline(c.process.title)}</h2>
      ${tile(c.process.image, 'tile-process')}
    </div>

    <ol class="process-steps">
      ${c.process.steps
        .map(
          (step, i) => `<li>
        <span class="d step-num" aria-hidden="true">${String(i + 1).padStart(2, '0')}</span>
        <div><h3 class="d card-title">${esc(step.title)}</h3><p class="step-copy">${esc(step.copy)}</p></div>
      </li>`
        )
        .join('\n      ')}
      <li class="process-close">
        <p class="lede-bold">${esc(c.process.close)}</p>
      </li>
    </ol>
  </div>
</section>

<!-- ============ TEAM ============ -->
<section class="band band-cream section-team" id="team">
  <div class="inner stack-lg">
    <div class="team-head">
      <h2 class="d team-title">${esc(c.team.title)}</h2>
      <span class="script team-script" aria-hidden="true">${esc(c.team.script)}</span>
    </div>

    <div class="team-grid">
      ${c.team.members
        .map(
          (m) => `<figure>
        ${tile(m.image, 'tile-team')}
        <figcaption>
          <span class="d card-title">${esc(m.name)}</span>
          <span class="eb signal">${esc(m.role)}</span>
          <span class="mono muted">${esc(m.skills)}</span>
        </figcaption>
      </figure>`
        )
        .join('\n      ')}
    </div>
  </div>
</section>

<!-- ============ TESTIMONIALS ============ -->
<section class="band band-dark section-quotes" aria-labelledby="quotes-title">
  <div class="inner stack-lg">
    <div class="quotes-head">
      <p class="eb" id="quotes-title">${esc(c.testimonials.eyebrow)}</p>
      ${c.testimonials.note ? `<p class="mono ph quotes-note">${esc(c.testimonials.note)}</p>` : ''}
    </div>
    <div class="quotes-grid">
      ${c.testimonials.items
        .map(
          (q) => `<blockquote>
        <p class="ph quote-text">&#8220;${esc(q.quote)}&#8221;</p>
        <footer class="mono ph">${esc(q.name)}, ${esc(q.role)}<br>${esc(q.company)}</footer>
      </blockquote>`
        )
        .join('\n      ')}
    </div>
  </div>
</section>

<!-- ============ CONTACT ============ -->
<section class="band band-dark band-cobalt section-contact" id="contact">
  <div class="inner contact-grid">
    <div class="contact-intro">
      <p class="eb">${esc(c.contact.eyebrow)}</p>
      <h2 class="d contact-title">${multiline(c.contact.title)}</h2>
      <p class="lede">${esc(c.contact.lede)}</p>
      <div class="contact-details">
        <a class="mono ph" href="mailto:${esc(c.contact.email)}">${esc(c.contact.email)}</a>
        <span class="mono ph">${esc(c.contact.phone)}</span>
        <span class="mono ph">${esc(c.contact.location)}</span>
      </div>
      ${tile(c.contact.image, 'tile-contact')}
    </div>

    <form class="contact-form" id="contact-form" method="post" action="${esc(c.contact.form.endpoint)}"
          data-messages="${esc(JSON.stringify(c.contact.form.messages))}" novalidate>
      <div class="field">
        <label class="eb" for="f-name">Name</label>
        <input id="f-name" name="name" type="text" autocomplete="name" placeholder="Your name" required>
      </div>
      <div class="field">
        <label class="eb" for="f-email">Email</label>
        <input id="f-email" name="email" type="email" autocomplete="email" placeholder="you@company.com" required>
      </div>
      <div class="field">
        <label class="eb" for="f-brand">Brand</label>
        <input id="f-brand" name="brand" type="text" autocomplete="organization" placeholder="Company or brand name">
      </div>
      <div class="field">
        <label class="eb" for="f-need">What do you need</label>
        <select id="f-need" name="need">
          ${c.contact.form.needOptions.map((o) => `<option>${esc(o)}</option>`).join('\n          ')}
        </select>
      </div>
      <div class="field">
        <label class="eb" for="f-msg">Tell us more</label>
        <textarea id="f-msg" name="message" rows="4" placeholder="Where the brand is now, and where you want it to be."></textarea>
      </div>

      <!-- Bot trap: hidden from people, irresistible to scrapers. -->
      <div class="hp" aria-hidden="true">
        <label for="f-website">Website</label>
        <input id="f-website" name="website" type="text" tabindex="-1" autocomplete="off">
      </div>
${
  turnstile
    ? `      <div class="cf-turnstile" data-sitekey="${esc(turnstile)}" data-theme="dark"></div>\n`
    : ''
}      <button class="btn btn-invert" type="submit">${esc(c.contact.form.submitLabel)} ${arrow}</button>
      <p class="form-status mono" id="form-status" role="status" aria-live="polite"></p>
    </form>
  </div>
</section>

</main>

<footer class="band band-dark site-footer">
  <div class="inner footer-inner">
    <div class="footer-brand">
      <span class="wordmark">${esc(c.brand.wordmark)}<span class="dot" aria-hidden="true"></span></span>
      <span class="mono footer-tagline">${esc(c.brand.tagline)}</span>
    </div>
    <nav class="footer-nav" aria-label="Footer">
      ${navLinks('eb')}
      ${c.footer.social
        .map((s) => `<a class="eb ph" href="${esc(s.href)}" rel="me noopener">${esc(s.label)}</a>`)
        .join('\n      ')}
    </nav>
    <span class="mono footer-copy">${esc(c.brand.copyright)}</span>
  </div>
</footer>

${turnstile ? '<script src="https://challenges.cloudflare.com/turnstile/v0/api.js" async defer></script>\n' : ''}<script src="assets/js/main.js" defer></script>
</body>
</html>
`;
}
