/* Renders index.html from content.json. Markup and class names follow the Bou
   design system; all copy comes from the content object, never from here. */

const esc = (value) =>
  String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

/** Escaped, with **double asterisks** turned into <strong>. */
const rich = (value) => esc(value).replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');

/** Escaped, with newlines turned into line breaks — for display headings. */
const multiline = (value) => esc(value).split('\n').join('<br>');

const arrow = '<span class="arrow" aria-hidden="true">&#8594;</span>';

const button = (cta, style) =>
  `<a class="btn btn-${style}" href="${esc(cta.href)}">${esc(cta.label)} ${arrow}</a>`;

/** Stagger index for the reveal-on-scroll transition. */
const step = (i) => (i ? ` style="--i:${i}"` : '');

/* ---------- Media slots ----------
   Every picture on the page is a "media slot": content.json can put either an
   image or a video in it. A slot is a video when its src ends in a video
   extension, or when it says so with "type": "video". A video slot may carry a
   "poster" image for the frame shown before it plays. */

const VIDEO_SRC = /\.(mp4|webm|ogv|ogg|mov|m4v)$/i;

export const isVideo = (m) => String(m.type || '').toLowerCase() === 'video' || VIDEO_SRC.test(m.src);

/* Videos are muted and loop, because that is the only way a browser will let
   them play without being asked. The mute toggle beside them turns sound on. */
const media = (m, { className = '', eager = false, autoplay = false, decorative = false } = {}) => {
  const cls = className ? ` class="${className}"` : '';
  const label = decorative ? ' aria-hidden="true"' : ` aria-label="${esc(m.alt)}"`;

  if (!isVideo(m)) {
    const load = eager ? 'loading="eager" fetchpriority="high"' : 'loading="lazy"';
    return `<img${cls} src="${esc(m.src)}" alt="${decorative ? '' : esc(m.alt)}" ${load}>`;
  }

  return `<video${cls} src="${esc(m.src)}"${m.poster ? ` poster="${esc(m.poster)}"` : ''}${label}
        muted loop playsinline preload="${eager ? 'auto' : 'metadata'}"${autoplay ? ' autoplay' : ''}></video>`;
};

/* Sits beside the video, never inside it: the work cards are buttons, and a
   button cannot contain another button. */
const sound = (m, labels, { cls = '', id = '', hidden = false } = {}) =>
  isVideo(m)
    ? `<button class="sound${cls ? ` ${cls}` : ''}"${id ? ` id="${id}"` : ''}${hidden ? ' hidden' : ''}
          type="button" aria-pressed="false"
          aria-label="${esc(labels.unmuteLabel)}"
          data-label-unmute="${esc(labels.unmuteLabel)}" data-label-mute="${esc(labels.muteLabel)}">
          <svg class="i-off" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M11 5 6 9H2v6h4l5 4z"/><path d="M22 9l-6 6M16 9l6 6"/></svg>
          <svg class="i-on" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M11 5 6 9H2v6h4l5 4z"/><path d="M15.5 8.5a5 5 0 0 1 0 7M18.5 5.5a9 9 0 0 1 0 13"/></svg>
        </button>`
    : '';

/* Marks the box that hovering — or, where there is no hover, focusing —
   starts the video in. */
const box = (m) => (isVideo(m) ? ' data-media="video"' : '');

export function renderPage(c) {
  const navLinks = (cls) =>
    c.nav
      .map((item) => `<a${cls ? ` class="${cls}"` : ''} href="${esc(item.href)}">${esc(item.label)}</a>`)
      .join('\n      ');

  const wordmark = `${esc(c.brand.wordmark)}<span class="dot" aria-hidden="true"></span>`;

  const turnstile = c.contact.form.turnstileSiteKey;

  const labels = c.media;

  /* One marquee list, printed twice: the track scrolls by exactly half its
     width, so the second copy lands where the first began. */
  const marqueeList = `<ul>
      ${c.marquee.map((item) => `<li>${esc(item)}<i></i></li>`).join('\n      ')}
    </ul>`;

  /* Every work card opens the same dialog, filled from its data attributes. */
  const caseData = (item, title, kind) =>
    `data-title="${esc(title)}" data-kind="${esc(kind)}"
          data-brief="${esc(item.brief)}" data-did="${esc(item.did)}" data-result="${esc(item.result)}"
          data-src="${esc(item.image.src)}" data-alt="${esc(item.image.alt)}"
          data-type="${isVideo(item.image) ? 'video' : 'image'}" data-poster="${esc(item.image.poster || '')}"`;

  return `<!doctype html>
<!-- Generated by build.mjs from content.json — edit content.json, not this file. -->
<html lang="${esc(c.site.lang)}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(c.site.title)}</title>
<meta name="description" content="${esc(c.site.description)}">
<meta name="theme-color" content="${esc(c.site.themeColor)}">

<meta property="og:type" content="website">
<meta property="og:title" content="${esc(c.site.ogTitle)}">
<meta property="og:description" content="${esc(c.site.ogDescription)}">
<meta property="og:image" content="${esc(c.site.ogImage)}">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Allura&family=Anton&family=Archivo:wght@400;500;600;700;800&family=Lekton:wght@400;700&family=Tinos:wght@400;700&display=swap">
<link rel="stylesheet" href="assets/css/styles.css">
</head>
<body>

<a class="skip-link" href="#top">Skip to content</a>

<div class="progress" aria-hidden="true"><span id="progress-bar"></span></div>

<header class="nav" id="nav" data-on="dark">
  <div class="nav-in">
    <a class="mark" href="#top">${wordmark}<span class="sr-only"> — home</span></a>

    <nav class="nav-links" aria-label="Primary">
      ${navLinks('eb')}
      ${button(c.cta, 'invert')}
    </nav>

    <button class="nav-toggle" type="button" aria-label="Open menu" aria-expanded="false" aria-controls="drawer">
      <span></span>
    </button>
  </div>
</header>

<div class="drawer" id="drawer" hidden>
  ${navLinks('')}
  <a href="${esc(c.cta.href)}">${esc(c.cta.label)}</a>
</div>

<main>

<!-- ============ HERO ============ -->
<section class="band ink dark hero" id="top" data-nav="dark"${box(c.hero.image)}>
  <div class="hero-media" aria-hidden="true">
    ${media(c.hero.image, { eager: true, autoplay: true, decorative: true })}
  </div>
  <div class="hero-scrim" aria-hidden="true"></div>
  <div class="hero-scrim-b" aria-hidden="true"></div>

  <div class="inner">
    <div class="hero-kicker">
      <span class="rule" aria-hidden="true"></span>
      <p class="eb">${esc(c.hero.eyebrow)}</p>
    </div>
    <h1 class="d d-hero">${multiline(c.hero.title)}</h1>
    <p class="lead">${esc(c.hero.lede)}</p>
    <ul class="hero-tags">
      ${c.hero.tags.map((t) => `<li>${esc(t)}</li>`).join('\n      ')}
    </ul>
    <div class="hero-cta">
      ${c.hero.buttons.map((b) => button(b, b.style)).join('\n      ')}
    </div>
    <p class="scroll-hint eb" aria-hidden="true">${esc(c.hero.scrollLabel)} <i></i></p>
  </div>
  ${sound(c.hero.image, labels, { cls: 'sound-hero' })}
</section>

<!-- ============ WHO ARE WE ============ -->
<section class="band cream pad" id="about" data-nav="light">
  <div class="inner about-grid">
    <div class="about-l">
      <p class="eb" data-reveal>${esc(c.about.eyebrow)}</p>
      <h2 class="d d-1" data-reveal${step(1)}>${multiline(c.about.title)}</h2>
      <p class="lead" data-reveal${step(2)}>${rich(c.about.lede)}</p>
      <div class="pull" data-reveal${step(3)}>
        <span class="bar" aria-hidden="true"></span>
        <p>${esc(c.about.statement)}</p>
      </div>
    </div>

    <div class="about-r">
      <p class="eb" data-reveal>${esc(c.about.touchpointsTitle)}</p>
      <ul class="touch">
        ${c.about.touchpoints
          .map((t, i) => `<li data-reveal${step(i + 1)}><span>${esc(t)}</span></li>`)
          .join('\n        ')}
      </ul>
      <p class="mono about-note" data-reveal${step(c.about.touchpoints.length + 1)}>${esc(c.about.note)}</p>
    </div>
  </div>
</section>

<!-- ============ MARQUEE ============ -->
<div class="marq" data-nav="dark" aria-hidden="true">
  <div class="marq-track">
    ${marqueeList}
    ${marqueeList}
  </div>
</div>

<!-- ============ SERVICES ============ -->
<section class="band cobalt dark pad-lg" id="services" data-nav="dark">
  <div class="inner">
    <div class="head">
      <div class="head-l">
        <p class="eb" data-reveal>${esc(c.services.eyebrow)}</p>
        <h2 class="d d-1" data-reveal${step(1)}>${multiline(c.services.title)}</h2>
      </div>
      <p class="lead" data-reveal${step(2)}>${esc(c.services.note)}</p>
    </div>

    <div class="svc-grid">
      ${c.services.columns
        .map(
          (col, i) => `<div class="svc" data-reveal${step(i)}>
        <h3 class="d d-4">${esc(col.title)}</h3>
        <ul>
          ${col.items.map((item) => `<li><span>${esc(item)}</span></li>`).join('\n          ')}
        </ul>
      </div>`
        )
        .join('\n      ')}
    </div>

    <div class="svc-foot">
      <p class="d d-3" data-reveal>${multiline(c.services.statement)}</p>
      <span data-reveal${step(1)}>${button(c.services.cta, 'invert')}</span>
    </div>
  </div>
</section>

<!-- ============ WORK ============ -->
<section class="band cream pad" id="work" data-nav="light">
  <div class="inner">
    <div class="head">
      <div class="head-l">
        <p class="eb" data-reveal>${esc(c.work.eyebrow)}</p>
        <h2 class="d d-1" data-reveal${step(1)}>${esc(c.work.title)}</h2>
      </div>
      <p class="mono" data-reveal${step(2)} style="max-width:32ch">${esc(c.work.note)}</p>
    </div>

    <div class="work-grid">
      <div class="work-item feature"${box(c.work.feature.image)} data-reveal>
        <button class="work-card lead-card" type="button"
          ${caseData(c.work.feature, c.work.feature.title, c.work.feature.kicker)}>
          <span class="shot">
            ${media(c.work.feature.image)}
            <span class="open eb"><span>${esc(c.work.openLabel)}</span>${arrow}</span>
          </span>
          <span class="work-meta">
            <span class="eb">${esc(c.work.feature.kicker)}</span>
            <span class="d d-3">${esc(c.work.feature.title)}</span>
            <span class="ph work-result">${esc(c.work.feature.result)}</span>
          </span>
        </button>
        ${sound(c.work.feature.image, labels)}
      </div>

      ${c.work.items
        .map(
          (item, i) => `<div class="work-item small"${box(item.image)} data-reveal${step(i + 1)}>
        <button class="work-card small" type="button"
          ${caseData(item, item.caseTitle, item.caseKind)}>
          <span class="shot">
            ${media(item.image)}
            <span class="open eb"><span>${esc(c.work.openLabelShort)}</span>${arrow}</span>
          </span>
          <span class="work-meta">
            <span class="eb">${esc(item.kicker)}</span>
            <span class="ph">${esc(item.client)}</span>
          </span>
        </button>
        ${sound(item.image, labels)}
      </div>`
        )
        .join('\n\n      ')}
    </div>

    <div class="work-foot">
      <p class="mono ph" data-reveal>${esc(c.work.footNote)}</p>
      <span data-reveal${step(1)}>${button(c.work.cta, 'outline')}</span>
    </div>
  </div>
</section>

<!-- ============ PROCESS ============ -->
<section class="band cobalt dark pad-lg" id="process" data-nav="dark">
  <div class="inner proc">
    <div class="proc-sticky">
      <p class="eb" data-reveal>${esc(c.process.eyebrow)}</p>
      <h2 class="d d-2" data-reveal${step(1)}>${multiline(c.process.title)}</h2>
      <div class="bignum" aria-hidden="true">
        <b id="step-num">01</b>
        <em id="step-title">${esc(c.process.steps[0].title)}</em>
      </div>
      <div class="par-wrap"${box(c.process.image)} data-par="0.05" data-reveal${step(2)}>
        ${media(c.process.image)}
        ${sound(c.process.image, labels)}
      </div>
    </div>

    <ol class="proc-list">
      ${c.process.steps
        .map((s, i) => {
          const n = String(i + 1).padStart(2, '0');
          return `<li class="step" data-n="${n}" data-title="${esc(s.title)}">
        <span class="step-rail" aria-hidden="true"><i></i></span>
        <span>
          <h3 class="d d-4">${n} &#8212; ${esc(s.title)}</h3>
          <p>${esc(s.copy)}</p>
        </span>
      </li>`;
        })
        .join('\n      ')}
      <li>
        <p class="proc-close" data-reveal>${esc(c.process.close)}</p>
      </li>
    </ol>
  </div>
</section>

<!-- ============ TEAM ============ -->
<section class="band cream pad" id="team" data-nav="light">
  <div class="inner">
    <div class="team-head">
      <h2 class="d d-1" data-reveal>${esc(c.team.title)}</h2>
      <span class="script" data-reveal${step(1)} aria-hidden="true">${esc(c.team.script)}</span>
    </div>

    <div class="team-grid">
      ${c.team.members
        .map(
          (m, i) => `<div class="member"${box(m.image)} data-reveal${step(i)}>
        <figure>${media(m.image)}${sound(m.image, labels)}</figure>
        <div class="member-meta">
          <span class="d d-3">${esc(m.name)}</span>
          <span class="eb">${esc(m.role)}</span>
          <span class="mono-s">${esc(m.skills)}</span>
        </div>
      </div>`
        )
        .join('\n      ')}
    </div>
  </div>
</section>

<!-- ============ TESTIMONIALS ============ -->
<section class="band ink dark pad" id="clients" data-nav="dark" aria-labelledby="quotes-title">
  <div class="inner">
    <div class="head">
      <p class="eb" id="quotes-title" data-reveal>${esc(c.testimonials.eyebrow)}</p>
      ${
        c.testimonials.note
          ? `<p class="mono ph" data-reveal${step(1)} style="font-size:13px">${esc(c.testimonials.note)}</p>`
          : ''
      }
    </div>
    <div class="quotes">
      ${c.testimonials.items
        .map(
          (q, i) => `<blockquote class="quote" data-reveal${step(i)}>
        <p class="ph">&#8220;${esc(q.quote)}&#8221;</p>
        <footer class="mono-s ph">${esc(q.name)}, ${esc(q.role)}<br>${esc(q.company)}</footer>
      </blockquote>`
        )
        .join('\n      ')}
    </div>
  </div>
</section>

<!-- ============ CONTACT ============ -->
<section class="band cobalt dark pad-lg" id="contact" data-nav="dark">
  <div class="inner contact-grid">
    <div class="contact-l">
      <p class="eb" data-reveal>${esc(c.contact.eyebrow)}</p>
      <h2 class="d d-1" data-reveal${step(1)}>${multiline(c.contact.title)}</h2>
      <p class="lead" data-reveal${step(2)}>${esc(c.contact.lede)}</p>
      <div class="contact-lines" data-reveal${step(3)}>
        <a class="mono ph" href="mailto:${esc(c.contact.email)}">${esc(c.contact.email)}</a>
        <span class="mono ph">${esc(c.contact.phone)}</span>
        <span class="mono ph">${esc(c.contact.location)}</span>
      </div>
      <div class="par-wrap"${box(c.contact.image)} data-par="0.04" data-reveal${step(4)}>
        ${media(c.contact.image)}
        ${sound(c.contact.image, labels)}
      </div>
    </div>

    <div class="contact-r" data-reveal>
      <form id="contact-form" method="post" action="${esc(c.contact.form.endpoint)}"
            data-messages="${esc(JSON.stringify(c.contact.form.messages))}" novalidate>
        <div class="field">
          <input id="f-name" name="name" type="text" placeholder=" " autocomplete="name" required>
          <label for="f-name">Name</label>
        </div>
        <div class="field">
          <input id="f-email" name="email" type="email" placeholder=" " autocomplete="email" required>
          <label for="f-email">Email</label>
        </div>
        <div class="field">
          <input id="f-brand" name="brand" type="text" placeholder=" " autocomplete="organization">
          <label for="f-brand">Brand</label>
        </div>
        <div class="field sel">
          <select id="f-need" name="need">
            ${c.contact.form.needOptions.map((o) => `<option>${esc(o)}</option>`).join('\n            ')}
          </select>
          <label for="f-need">What do you need</label>
        </div>
        <div class="field">
          <textarea id="f-msg" name="message" rows="4" placeholder=" "></textarea>
          <label for="f-msg">Tell us more</label>
        </div>

        <!-- Bot trap: hidden from people, irresistible to scrapers. -->
        <div class="hp" aria-hidden="true">
          <label for="f-website">Website</label>
          <input id="f-website" name="website" type="text" tabindex="-1" autocomplete="off">
        </div>
${
  turnstile
    ? `        <div class="cf-turnstile" data-sitekey="${esc(turnstile)}" data-theme="dark"></div>\n`
    : ''
}        <button class="btn btn-invert" type="submit" style="align-self:flex-start">${esc(c.contact.form.submitLabel)} ${arrow}</button>
        <p class="form-note mono" id="form-status" role="status" aria-live="polite"></p>
      </form>

      <div class="sent" id="sent" hidden tabindex="-1">
        <p class="d d-4">${esc(c.contact.form.sent.title)}</p>
        <p>${esc(c.contact.form.sent.copy)}</p>
        <button class="btn btn-ghost" id="send-again" type="button">${esc(c.contact.form.sent.againLabel)} ${arrow}</button>
      </div>
    </div>
  </div>
</section>

</main>

<footer class="band ink dark" data-nav="dark" style="padding-block:clamp(48px,6vw,72px)">
  <div class="inner foot">
    <div class="foot-brand">
      <span class="mark">${wordmark}</span>
      <span class="mono-s foot-tagline">${esc(c.brand.tagline)}</span>
    </div>
    <nav class="foot-links" aria-label="Footer">
      ${navLinks('eb')}
      ${c.footer.social
        .map((s) => `<a class="eb ph" href="${esc(s.href)}" rel="me noopener">${esc(s.label)}</a>`)
        .join('\n      ')}
    </nav>
    <span class="mono-s foot-copy">${esc(c.brand.copyright)}</span>
  </div>
</footer>

<dialog class="case" id="case" aria-labelledby="case-title">
  <div class="case-in">
    <div class="case-top">
      <div class="case-head">
        <span class="eb" id="case-kind"></span>
        <h2 class="d d-2" id="case-title"></h2>
      </div>
      <button class="case-close" id="case-close" type="button" aria-label="Close">
        <svg width="16" height="16" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M1 1l14 14M15 1L1 15"/></svg>
      </button>
    </div>
    <div class="case-media">
      <img class="case-img" id="case-img" src="" alt="" hidden>
      <video class="case-img" id="case-video" muted loop playsinline preload="metadata" hidden></video>
      ${sound({ type: 'video', src: '', alt: '' }, labels, {
        cls: 'case-sound',
        id: 'case-sound',
        hidden: true
      })}
    </div>
    <dl>
      <div><dt class="eb">${esc(c.work.caseLabels.brief)}</dt><dd id="case-brief"></dd></div>
      <div><dt class="eb">${esc(c.work.caseLabels.did)}</dt><dd id="case-did"></dd></div>
      <div><dt class="eb">${esc(c.work.caseLabels.result)}</dt><dd class="ph" id="case-result"></dd></div>
    </dl>
    <a class="btn btn-primary" id="case-cta" href="${esc(c.work.caseCta.href)}">${esc(c.work.caseCta.label)} ${arrow}</a>
  </div>
</dialog>

${turnstile ? '<script src="https://challenges.cloudflare.com/turnstile/v0/api.js" async defer></script>\n' : ''}<script src="assets/js/main.js" defer></script>
</body>
</html>
`;
}
